Issue #5: Allow passing in PHP binary path.

diff --git a/check_php b/check_php
--- a/check_php
+++ b/check_php
@@ -69,6 +69,8 @@ print_usage() {
 	printf "                         nagios warning/error if the configuration does not match.\n"
 	printf "                         Use multiple times to check against multiple configurations.\n"
 	printf "                         Example: -c \"date.timezone\" w -c \"Europe/Berlin\" e\n\n"
+	printf "  -p <path>              [optional] Define the path to the PHP binary that shall be used.\n"
+	printf "                         If no value is given, the current user's default PHP version will be checked.\n\n"
 	printf "  -v                     Be verbose (Show PHP Version and Zend Engine Version)\n\n"
 	printf "  -h                     Display help\n\n"
 	printf "  -V                     Display version\n"
@@ -79,7 +81,6 @@ print_version() {
 	printf "Author:  %s (%s)\n" "${INFO_AUTHOR}" "${INFO_GPGKEY}"
 	printf "License: %s\n" "${INFO_LICENSE}"
 }
-
 
 merge_text() {
 	CURR_TEXT="$1"
@@ -254,6 +255,31 @@ check_blacklisted_module() {
 	fi
 }
 
+# Fetch PHP
+# ---------
+# Checks the given arguments for a '-p' option and sets the PHP
+# variable accordingly.
+fetch_php() {
+	while test -n "$1"; do
+		case "$1" in
+			# PHP binary otion.
+			-p)
+				shift
+				PHP="$1"
+
+				# Whether the given PHP binary doesn't exist.
+				if [ ! -x $PHP ]; then
+					echo "PHP binary not found at \"$PHP\" for option \"-p\"."
+					exit $EXIT_UNKNOWN
+				fi
+
+				break
+				;;
+		esac
+		shift
+	done
+}
+
 
 ################################################################################
 #
@@ -276,6 +302,8 @@ elif [ "$1" = "-V" ]; then
 	exit $EXIT_OK
 fi
 
+# Check for PHP binary option
+fetch_php "$@"
 
 # Extended Status Message
 MSG_STARTUP=""
@@ -392,7 +420,7 @@ while test -n "$1"; do
 
 			# Check valid exit code
 			if [ "$SEVERITY" != "w" ] && [ "$SEVERITY" != "e" ]; then
-				echo "Invalid value \"$SEVERITY\" for option \"-m\"."
+				echo "Invalid severity value \"$SEVERITY\" for option \"-m\" and module \"$MODULE\"."
 				exit $EXIT_UNKNOWN
 			fi
 
@@ -432,9 +460,10 @@ while test -n "$1"; do
 
 			# Check valid exit code
 			if [ "$SEVERITY" != "w" ] && [ "$SEVERITY" != "e" ]; then
-				echo "Invalid value \"$SEVERITY\" for option \"-b\"."
+				echo "Invalid severity \"$SEVERITY\" for option \"-b\" and module \"$MODULE\"."
 				exit $EXIT_UNKNOWN
 			fi
+
 
 			# Execute Command
 			TMP_TEXT="$(check_blacklisted_module "$MODULE")"
@@ -477,7 +506,7 @@ while test -n "$1"; do
 
 			# Check valid exit code
 			if [ "$SEVERITY" != "w" ] && [ "$SEVERITY" != "e" ]; then
-				echo "Invalid value \"$SEVERITY\" for option \"-c\"."
+				echo "Invalid severity \"$SEVERITY\" for option \"-c\" and directive \"$CONFIG\"."
 				exit $EXIT_UNKNOWN
 			fi
 
@@ -505,7 +534,7 @@ while test -n "$1"; do
 			CNT_ALL=$((CNT_ALL+1))
 			;;
 
-		# ---- Be versbose
+		# ---- Be verbose
 		-v)
 			CMD="$PHP -v 2>/dev/null | grep -E '(^PHP)|(^Zend)' | awk -F'[,]' '{print \$1}' | awk -F'[(]' '{print \$1}' | awk -F'[-]' '{print \$1}'"
 			MSG_VERBOSE="$(eval "$CMD")"
@@ -515,6 +544,14 @@ while test -n "$1"; do
 			print_version
 			exit $EXIT_OK
 			;;
+
+		# ---- PHP binary
+		-p)
+			# The binary option is checked earlier. So just shift
+			# the path and move on.
+			shift
+			;;
+
 		*)
 			printf "Unknown argument: %s\n" "$1"
 			print_usage
